/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesIndexRouteImport } from './routes/series.index'
import { Route as SeriesIdRouteImport } from './routes/series.$id'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as ApiPublicXtreamRouteImport } from './routes/api/public/xtream'
import { Route as ApiPublicStreamRouteImport } from './routes/api/public/stream'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIdRoute = SeriesIdRouteImport.update({
  id: '/series/$id',
  path: '/series/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicXtreamRoute = ApiPublicXtreamRouteImport.update({
  id: '/api/public/xtream',
  path: '/api/public/xtream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamRoute = ApiPublicStreamRouteImport.update({
  id: '/api/public/stream',
  path: '/api/public/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/favorites': typeof FavoritesRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/movie/$id': typeof MovieIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/series/': typeof SeriesIndexRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
  '/api/public/xtream': typeof ApiPublicXtreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/favorites': typeof FavoritesRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/movie/$id': typeof MovieIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/series': typeof SeriesIndexRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
  '/api/public/xtream': typeof ApiPublicXtreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/favorites': typeof FavoritesRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/movie/$id': typeof MovieIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/series/': typeof SeriesIndexRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
  '/api/public/xtream': typeof ApiPublicXtreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/favorites'
    | '/live'
    | '/login'
    | '/movies'
    | '/search'
    | '/sitemap.xml'
    | '/movie/$id'
    | '/series/$id'
    | '/series/'
    | '/api/public/stream'
    | '/api/public/xtream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/favorites'
    | '/live'
    | '/login'
    | '/movies'
    | '/search'
    | '/sitemap.xml'
    | '/movie/$id'
    | '/series/$id'
    | '/series'
    | '/api/public/stream'
    | '/api/public/xtream'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/favorites'
    | '/live'
    | '/login'
    | '/movies'
    | '/search'
    | '/sitemap.xml'
    | '/movie/$id'
    | '/series/$id'
    | '/series/'
    | '/api/public/stream'
    | '/api/public/xtream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FavoritesRoute: typeof FavoritesRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  MoviesRoute: typeof MoviesRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MovieIdRoute: typeof MovieIdRoute
  SeriesIdRoute: typeof SeriesIdRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
  ApiPublicStreamRoute: typeof ApiPublicStreamRoute
  ApiPublicXtreamRoute: typeof ApiPublicXtreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$id': {
      id: '/series/$id'
      path: '/series/$id'
      fullPath: '/series/$id'
      preLoaderRoute: typeof SeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/xtream': {
      id: '/api/public/xtream'
      path: '/api/public/xtream'
      fullPath: '/api/public/xtream'
      preLoaderRoute: typeof ApiPublicXtreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream': {
      id: '/api/public/stream'
      path: '/api/public/stream'
      fullPath: '/api/public/stream'
      preLoaderRoute: typeof ApiPublicStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FavoritesRoute: FavoritesRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  MoviesRoute: MoviesRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MovieIdRoute: MovieIdRoute,
  SeriesIdRoute: SeriesIdRoute,
  SeriesIndexRoute: SeriesIndexRoute,
  ApiPublicStreamRoute: ApiPublicStreamRoute,
  ApiPublicXtreamRoute: ApiPublicXtreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
